definitions:
  config:
    /hippo:namespaces/myproject/slickSliderResponsiveSettingsCompound:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 53d810ea-666c-4f23-b822-2c5fa557c0ed
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 41c4b781-5229-43db-ba2b-ef63b99062b1
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: a44c9a1f-faca-4a11-b9d2-e413f3f5450a
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.myproject.com/myproject/nt/1.0
          /breakpoint:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:breakpoint
            hipposysedit:primary: false
            hipposysedit:type: Long
          /settings:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:settings
            hipposysedit:primary: false
            hipposysedit:type: myproject:slickSliderSettingsCompound
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:slickSliderResponsiveSettingsCompound
          myproject:breakpoint: 0
          /myproject:settings:
            jcr:primaryType: myproject:slickSliderSettingsCompound
            myproject:arrows: true
            myproject:autoplay: false
            myproject:autoplaySpeed: 3000
            myproject:dots: false
            myproject:dotsStyle: dots
            myproject:fade: false
            myproject:infinite: true
            myproject:pauseOnDotsHover: false
            myproject:pauseOnFocus: false
            myproject:pauseOnHover: false
            myproject:rows: 1
            myproject:slidesPerRow: 1
            myproject:slidesToScroll: 1
            myproject:vertical: false
            myproject:slidesToShow: 4
            myproject:speed: 500
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /breakpoint:
            jcr:primaryType: frontend:plugin
            caption: Breakpoint
            field: breakpoint
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /settings:
            jcr:primaryType: frontend:plugin
            caption: Settings
            field: settings
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
