definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:myproject/hst:sites/myproject
          /react:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:myproject/hst:sites/react
            hst:pagemodelapi: resourceapi
            hst:homepage: homepage
            hst:responseheaders: ['Access-Control-Allow-Origin: http://localhost:3000',
              'Access-Control-Allow-Credentials: true']
            /preview:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:mount
              hst:homepage: homepage
              hst:mountpoint: /hst:myproject/hst:sites/react
              hst:pagemodelapi: resourceapi
              hst:responseheaders: ['Access-Control-Allow-Origin: http://localhost:3000',
                'Access-Control-Allow-Credentials: true']
              hst:type: preview
          /api:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:alias: api
            hst:ismapped: false
            hst:namedpipeline: HalRestApiPipeline
            hst:types: [rest]
            hst:mountpoint: /hst:myproject/hst:sites/urlrewriter
