definitions:
  config:
    /hst:hst/hst:configurations/react/hst:abstractpages/base:
      jcr:primaryType: hst:component
      /promoBar:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/promoBar
      /drawer:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/drawer
      /footerMenu:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [menu]
        hst:parametervalues: [footer]
      /footerSocial:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [menu]
        hst:parametervalues: [footerSocial]
      /globalElements:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsDocumentComponent
        hst:parameternames: [document]
        hst:parametervalues: [global-elements]
      /navigation:
        jcr:primaryType: hst:component
        hst:componentclassname: org.example.components.MenuItemBanners
        hst:parameternames: [menu]
        hst:parametervalues: [main]
