definitions:
  config:
    /hst:hst/hst:configurations/react/hst:abstractpages/base:
      jcr:primaryType: hst:component
      /navigation:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/navigation
      /globalElements:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/globalElements
