definitions:
  config:
    /hst:hst/hst:configurations/react/hst:abstractpages/base:
      jcr:primaryType: hst:component
      /menu:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', main]
