definitions:
  config:
    /hst:hst/hst:configurations/react/hst:pages/product-detail:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        /ProductDetail:
          jcr:primaryType: hst:component
          hst:referencecomponent: hst:components/ProductDetail
        /Banner:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsDocumentComponent
          hst:parameternames: [document]
          hst:parametervalues: ['products/banners/${1}']
        /FrequentlyViewedTogether:
          jcr:primaryType: hst:containeritemcomponent
          hst:componentdefinition: hst:components/react-catalog/PathwaysRecommendations
          hst:parameternames: [document, productId]
          hst:parametervalues: [components/pathways-and-recommendations/pdp-frequently-viewed-together,
            '${1}']
        /FrequentlyBoughtTogether:
          jcr:primaryType: hst:containeritemcomponent
          hst:componentdefinition: hst:components/react-catalog/PathwaysRecommendations
          hst:parameternames: [document, productId]
          hst:parametervalues: [components/pathways-and-recommendations/pdp-frequently-bought-together,
            '${1}']
