definitions:
  config:
    /hst:hst/hst:configurations/react/hst:pages/product-detail-template:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        /ProductDetail:
          jcr:primaryType: hst:component
          hst:referencecomponent: hst:components/ProductDetail
          hst:parameternames: [productId]
          hst:parametervalues: [82473fam]
          /product-detail-bottom-1:
            jcr:primaryType: hst:containercomponentreference
            hst:referencecomponent: product-detail/product-detail-bottom-1
          /product-detail-bottom-2:
            jcr:primaryType: hst:containercomponentreference
            hst:referencecomponent: product-detail/product-detail-bottom-2
          /product-detail-bottom-3:
            jcr:primaryType: hst:containercomponentreference
            hst:referencecomponent: product-detail/product-detail-bottom-3
