definitions:
  config:
    /hst:hst/hst:configurations/react/hst:pages/product-detail:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        /ProductDetail:
          jcr:primaryType: hst:component
          hst:referencecomponent: hst:components/ProductDetail
